### ISSUE TITLE
[Duplicate?] CANCEL_PRINT macro -> Bed collides with bottom of printer when canceling and then homing

### ISSUE THREAD

**Issue by McSneaky** [Phil1988/FreeDi#107]
**Describe the bug**
When you cancel print, bed goes to the bottom of printer, now when you try to start new print / home after it, it tries to move down some more in it's homing procedure, which makes bed collide with printer frame and z axis belt will skip steps

**Expected behavior**
Bed won't collide. Maybe not move bed to totally bottom of printer when colliding, or adding check into homing, so homing doesn't try to lower bed any more

**To Reproduce**
1. Start pring
2. Cancel print
3. Home printer
4. See the bed colliding

**Console output**
I'll try to get it next time it happens

**Base (please complete the following information):**
 - X3seriesLCD firmware version: v1.30-0-g388855ca
 - OS: Armbian-unofficial 24.2.0-trunk bookworm
 - Source: FreeDi image
 - Mainboard: Stock mainboard, I think was X-4

**Comment by McSneaky** [comment]
If it happens again, I can try to get console output and ensure in steps

Idea I had is just to make cancel print to not bottom out. I can make PR for that

**Comment by Phil1988** [comment]
please show me your 
[gcode_macro G28]
[gcode_macro CANCEL_PRINT]
from the macros.cfg
and your 
[stepper_z]
from the printer.cfg

and what printer do you have?

**Comment by McSneaky** [comment]
Everything is stock that came with FreeDi 1.30, except Cartographer section

<details>
<summary>[gcode_macro G28]</summary>

```yml
[gcode_macro G28]
rename_existing: G28.1
gcode:
    {% set home_all = ('X' in rawparams.upper() and 'Y' in rawparams.upper() and 'Z' in rawparams.upper()) or 
                      ('X' not in rawparams.upper() and 'Y' not in rawparams.upper() and 'Z' not in rawparams.upper()) %}
    {% set home_current_x = printer.configfile.settings['tmc2209 stepper_x'].run_current * 0.8 %}
    {% set home_current_y = printer.configfile.settings['tmc2209 stepper_y'].run_current * 0.8 %}
    
    {% set init_XY_move = 30 %}
    #{% set y_init_move = 5 %}
    {% set z_clearance = 2 %}

    {% set home_all_final_position_x = printer.toolhead.axis_maximum.x / 2 %}
    {% set home_all_final_position_y = printer.toolhead.axis_maximum.y - 30 %}
    {% set home_all_final_position_z = 20 %}

    # If homing should at least move X or Y axis
    {% if home_all or 'X' in rawparams.upper() or 'Y' in rawparams.upper() %}     
        # Check if Z is homed
        {% if 'z' in printer.toolhead.homed_axes %}
            {% set Z_axis_was_homed = true %}                                                                       ; Set Z_axis_was_homed to true if Z is already homed
            G91                                                                                                     ; Use relative positioning
            G1 Z2 F600                                                                                              ; Move bed down
            G90                                                                                                     ; Use absolute positioning
        {% else %}
            {% set Z_axis_was_homed = false %}                                                                      ; Set Z_axis_was_homed to false if Z is not homed
            FORCE_MOVE STEPPER=stepper_z DISTANCE={z_clearance} VELOCITY=10                                         ; Move bed down
        {% endif %}
    {% endif %}

    {% if home_all or 'X' in rawparams.upper() or 'Y' in rawparams.upper() %} 
        G91                                                                                                         ; Use relative positioning
        FORCE_MOVE STEPPER=stepper_x DISTANCE={init_XY_move} VELOCITY=40                                            ; Move X a little before homing
        G90                                                                                                         ; Use absolute positioning
    {% endif %}

    # Home X
    {% if home_all or 'X' in rawparams.upper() %}        

        SET_TMC_CURRENT STEPPER=stepper_x CURRENT={home_current_x}                                                  ; Lower motor current
        G28.1 X                                                                                                     ; Home X
        SET_TMC_CURRENT STEPPER=stepper_x CURRENT={printer.configfile.settings['tmc2209 stepper_x'].run_current}    ; Set motor current to the previous value
        G1 X10 F1200                                                                                                ; Move X-axis slightly    
    {% endif %}

    # Home Y
    {% if home_all or 'Y' in rawparams.upper() %}
        SET_TMC_CURRENT STEPPER=stepper_y CURRENT={home_current_y}                                                  ; Lower motor current
        G28.1 Y                                                                                                     ; Home Y
        SET_TMC_CURRENT STEPPER=stepper_y CURRENT={printer.configfile.settings['tmc2209 stepper_y'].run_current}    ; Set motor current to the previous value
        G1 Y10 F1200                                                                                                ; Move Y-axis slightly    
    {% endif %}

    # Raise the bed again if only X or only Y axes were homed
    {% if not (home_all or 'Z' in rawparams.upper()) %}
        {% if Z_axis_was_homed %}
            G91                                                                                                     ; Use relative positioning
            G1 Z-2 F600                                                                                             ; Raise the bed back again
        {% else %}
            FORCE_MOVE STEPPER=stepper_z DISTANCE=-{z_clearance} VELOCITY=10                                        ; Raise the bed back again
        {% endif %}
    {% endif %}

    # Home Z
    {% if home_all or 'Z' in rawparams.upper() %}
        G28.1 Z                                                                                                     ; Home Z
        G90                                                                                                         ; Set absolute positioning
        G1 Z{home_all_final_position_z}                                                                             ; Move bed down   
    {% endif %}

    # Move to the final position if all axes were homed
    {% if home_all %}
        G90                                                                                                         ; Set absolute positioning
        G1 X{home_all_final_position_x} Y{home_all_final_position_y} Z{home_all_final_position_z} F7800             ; Move to the rear center
    {% endif %}

```
</details>

<details>
<summary>[gcode_macro CANCEL_PRINT]</summary>

```yml
[gcode_macro CANCEL_PRINT]
rename_existing: BASE_CANCEL_PRINT
gcode:

    {% set max_z = printer.configfile.config["stepper_z"]["position_max"]|float %}
	{% if (printer.toolhead.position.z + 12) < max_z %}
        {% set z_hop = 2  %}
    {% else %}
        {% set z_hop = 0 %}
    {% endif %}
	
	G91                                                                                                            ; Relative positioning
	G1 Z{z_hop} F600                                                                                               ; Do a tiny z-hop
    G90                                                                                                            ; Absolute positioning


    G1 X{printer.toolhead.axis_maximum.x/2} Y{printer.toolhead.axis_maximum.y-40} F12000
    CLEAR_PAUSE
    SDCARD_RESET_FILE

    PRINT_END
    BASE_CANCEL_PRINT

```
</details>



<details>
<summary>[probe] (I don't have Probe, I have Cartographer [scanner])</summary>

```yml
[scanner]
mcu: scanner            
#   Offsets are measured from the centre of your coil, to the tip of your nozzle 
#   on a level axis. It is vital that this is accurate. 
x_offset: 0                          
#    adjust for your cartographers offset from nozzle to middle of coil
y_offset: 25                         
#    adjust for your cartographers offset from nozzle to middle of coil
backlash_comp: 0.5
#   Backlash compensation distance for removing Z backlash before measuring
#   the sensor response.
sensor: cartographer
#    this must be set as cartographer unless using IDM etc.
sensor_alt: carto
#    alternate name to call commands. CARTO_TOUCH etc      
mesh_runs: 1
#    Number of passes to make during mesh scan.

[bed_mesh]
zero_reference_position: 162.5, 162.5    
#    set this to the middle of your bed
speed: 200
#    movement speed of toolhead during bed mesh
horizontal_move_z: 5
#    height of scanner during bed mesh scan
mesh_min: 25, 20
#    start point of bed mesh [X, Y]
mesh_max: 315, 315
#    end point of bed mesh [X, Y]
probe_count: 30, 30
algorithm: bicubic
```
</details>

<details>
<summary>[stepper_z]</summary>

```yml
[stepper_z]
step_pin:PC10
dir_pin:PA15
enable_pin: !PC11
microsteps: 16
rotation_distance: 8
full_steps_per_rotation: 200
endstop_pin:probe:z_virtual_endstop
position_max: 322
position_min: -2
homing_speed: 10
homing_retract_dist: 0.0 # Must be set to 0 by Carto
second_homing_speed: 8
homing_positive_dir:false
step_pulse_duration:0.000002
```
</details>
